import 'package:flutter/material.dart';

import 'client_runtime.dart';
import 'media/watch_screen.dart';

class ClientHomeScreen extends StatelessWidget {
  const ClientHomeScreen({super.key, required this.runtime, required this.onResetRole});
  final ClientRuntime runtime;
  final VoidCallback onResetRole;
  @override Widget build(BuildContext context) => StreamBuilder<ClientRuntimeState>(stream: runtime.states, initialData: runtime.currentState, builder: (context, snapshot) => Scaffold(body: _LightShell(child: SafeArea(child: ListView(padding: const EdgeInsets.fromLTRB(26, 18, 26, 28), children: [
    _Top(action: onResetRole), const SizedBox(height: 46),
    const Text('Ebeveyn cihazı', style: _title), const SizedBox(height: 6),
    const Text('Bebek odası cihazını otomatik bul, QR tara veya IP adresini gir.', style: _subtitle),
    const SizedBox(height: 72),
    _Card(child: Column(children: const [SizedBox(height: 270, child: _Radar()), SizedBox(height: 8), Text('Ağda BabyCam aranıyor...', style: TextStyle(color: _navy, fontSize: 24, fontWeight: FontWeight.w900)), SizedBox(height: 8), Text('UDP discovery aktif; bulamazsa QR veya IP kullan.', style: TextStyle(color: _slate, fontSize: 18))])),
    const SizedBox(height: 34), const Text('Bulunan cihazlar', style: TextStyle(color: _navy, fontSize: 30, fontWeight: FontWeight.w900)), const SizedBox(height: 18),
    const _Device(title: 'Bebek Odası', ip: '192.168.1.20:8080', chip: 'Güçlü sinyal'), const SizedBox(height: 22), const _Device(title: 'Salon yedek cihaz', ip: '192.168.1.34:8080', chip: 'Beklemede', muted: true),
    const SizedBox(height: 48),
    Container(padding: const EdgeInsets.all(28), decoration: _cardDecoration(dark: true), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [const Text('Bağlanma yöntemi', style: TextStyle(color: Colors.white, fontSize: 25, fontWeight: FontWeight.w900)), const SizedBox(height: 22), Container(height: 58, decoration: BoxDecoration(color: Colors.white, borderRadius: BorderRadius.circular(24)), alignment: Alignment.centerLeft, padding: const EdgeInsets.symmetric(horizontal: 24), child: const Text('192.168.1.20:8080', style: TextStyle(color: Color(0xFFF5F7FB), fontSize: 20)))])),
    const SizedBox(height: 170), Row(children: [Expanded(child: SizedBox(height: 72, child: FilledButton(onPressed: () {}, style: FilledButton.styleFrom(backgroundColor: _mint, shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(28))), child: const Text('QR Tara', style: TextStyle(color: _navy, fontSize: 22, fontWeight: FontWeight.w900))))), const SizedBox(width: 28), Expanded(child: SizedBox(height: 72, child: FilledButton(onPressed: () => Navigator.of(context).push(MaterialPageRoute(builder: (_) => WatchScreen(runtime: runtime))), style: FilledButton.styleFrom(backgroundColor: _pink, shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(28))), child: const Text('Bağlan', style: TextStyle(fontSize: 22, fontWeight: FontWeight.w900)))))]),
  ])))));
}
class _Device extends StatelessWidget { const _Device({required this.title, required this.ip, required this.chip, this.muted = false}); final String title; final String ip; final String chip; final bool muted; @override Widget build(BuildContext context) => Container(padding: const EdgeInsets.all(24), decoration: _cardDecoration(), child: Row(children: [CircleAvatar(radius: 32, backgroundColor: _mintSoft), const SizedBox(width: 22), Expanded(child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text(title, style: const TextStyle(color: _navy, fontSize: 23, fontWeight: FontWeight.w900)), const SizedBox(height: 6), Text(ip, style: const TextStyle(color: _slate, fontSize: 19))])), _SmallChip(text: chip, color: muted ? const Color(0xFFE9EDF2) : const Color(0xFFFFDCE6))])); }
class _Radar extends StatelessWidget { const _Radar(); @override Widget build(BuildContext context) => CustomPaint(painter: _RadarPainter(), child: const SizedBox.expand()); }
class _RadarPainter extends CustomPainter { const _RadarPainter(); @override void paint(Canvas canvas, Size size) { final c = Offset(size.width/2, size.height/2-10); final p = Paint()..color=_pink..style=PaintingStyle.stroke..strokeWidth=6; for (final r in [52.0,92.0,132.0]) canvas.drawCircle(c,r,p); canvas.drawCircle(c,50,Paint()..color=_navy); canvas.drawCircle(c,16,Paint()..color=_mint); } @override bool shouldRepaint(covariant CustomPainter oldDelegate)=>false; }
class _LightShell extends StatelessWidget { const _LightShell({required this.child}); final Widget child; @override Widget build(BuildContext context)=>Container(decoration: const BoxDecoration(gradient: RadialGradient(center: Alignment(.55,-.75), radius: .85, colors: [_mintSoft, Color(0xFFFDF7F4), Color(0xFFF9F7FC)])), child: child); }
class _Card extends StatelessWidget { const _Card({required this.child}); final Widget child; @override Widget build(BuildContext context)=>Container(width: double.infinity, padding: const EdgeInsets.all(28), decoration: _cardDecoration(), child: child); }
class _Top extends StatelessWidget { const _Top({required this.action}); final VoidCallback action; @override Widget build(BuildContext context)=>Row(children:[const Text('09:41',style:TextStyle(color:_navy,fontWeight:FontWeight.w900,fontSize:18)),const Spacer(),TextButton(onPressed:action, child: const Text('Rol')),const Icon(Icons.signal_cellular_alt_rounded,color:_navy),const SizedBox(width:12),const Icon(Icons.battery_5_bar_rounded,color:_navy)]); }
class _SmallChip extends StatelessWidget { const _SmallChip({required this.text, required this.color}); final String text; final Color color; @override Widget build(BuildContext context)=>Container(padding: const EdgeInsets.symmetric(horizontal: 14, vertical: 7), decoration: ShapeDecoration(color: color, shape: const StadiumBorder()), child: Text(text, style: const TextStyle(color: _navy, fontWeight: FontWeight.w800, fontSize: 16))); }
BoxDecoration _cardDecoration({bool dark=false}) => BoxDecoration(color: dark ? _navy : Colors.white, borderRadius: BorderRadius.circular(34), border: Border.all(color: const Color(0xFFE2E8F0)), boxShadow: const [BoxShadow(color: Color(0x24111827), blurRadius: 28, offset: Offset(0, 16))]);
const _navy=Color(0xFF101B31); const _slate=Color(0xFF6E7686); const _pink=Color(0xFFFF708B); const _mint=Color(0xFF87D8CC); const _mintSoft=Color(0xFFD9F7F1); const _title=TextStyle(color:_navy,fontSize:42,height:1.05,fontWeight:FontWeight.w900); const _subtitle=TextStyle(color:_slate,fontSize:21,height:1.18);
